experiment_name: 'CVAEresnet50_sdd_trajnet' 
device: 'cuda:0'
# MODEL
model:
  name: 'CVAEresnetTraj'
  pretrain: ''
  save_name: 'CVAEresnet50_sdd_short'
  kwargs:
    obs_len: 8
    pred_len: 12  # in timesteps
    lastlayer_dim: 128
    z_dim: 512
    sigma: 1.0
    segmentation_model_fp: 'segmentation_models/SDD_segmentation.pth'
    use_features_only: False # If True the segmentation model only uses the
    semantic_classes: 6
    resnet_name: 'resnet50'
  # loss
  loss_function: 
    name: 'SceneCVAELoss'
    kwargs: {
      traj_weight: 1.0,
      kld_weight: 1.0
    }
      # loss_scale: 1000  # factor to scale the loss
#dataset

dataset:
  name: 'sdd'
  dataset_name: 'scene_dataset'
  num_goals: 1  # K_e
  num_traj: 20  # K_a
  train_data_path: '../dataset/SDD/train_trajnet.pkl'
  train_image_path: '../dataset/SDD/train'
  val_data_path: '../dataset/SDD/test_trajnet.pkl'
  val_image_path: '../dataset/SDD/test'
  test_data_path: '../dataset/SDD/test_trajnet.pkl'
  test_image_path: '../dataset/SDD/test'

  env_type: ''
  # data info
  resize: 0.25
  batch_size: 4
  obs_len: 8
  pred_len: 12
  num_workers: 4 
  prefetch_factor: 2
  # load_to_gpu: True
  # Ynet
  division_factor: 32 # use in Ynet the division factor must be 2^(len(encoder_channels))
  kernlen: 31  # (image) size of Gaussian kernel used for ground-truth Gaussian heatmap
  nsig: 4  # sigma of Gaussian kernel used for ground-truth Gaussian heatmap
  waypoints: [11]
  # For semantic map
  segmentation_model_fp: segmentation_models/SDD_segmentation.pth
  semantic_classes: 6
  use_features_only: False  # If True the segmentation model only uses the
  initTrajectoryModelFilePath: ''
  #Sampler
  sampler: 
    name: 'interval' # custom or interval
    trainkwargs:
      num_interval: 25 # for one epoch, the max num_interval for sampling
    valkwargs:
      num_interval: 9999999 # for one epoch, the max num_interval for sampling
  #collate:
  collate_name: 'scene_collate'

optim:
  name: 'Adam'
  kwargs:
    lr: 0.001
  # learning_rate: 0.0001
  num_epochs: 100

# TEST

test:
  # TTST
  use_TTST: False
  rel_threshold: 0.01
  # CWS
  use_CWS: False
  CWS_params: None

  eval_step: 4
  temperature: 1.0
  round: 3

unfreeze: 150  # Unfreeze semantic segmentation model weights after this # of epochs
viz_epoch: 10
extra_info_name: 'inputTemplate'