experiment_name: 'CVAEMLPLSTM_univ_trajnet' 
device: 'cpu'

# MODEL
model:
  name: 'CVAEMLPLSTM'
  pretrain: ''
  save_name: 'CVAEMLPLSTM_univ'
  kwargs:
    inp_size: 2
    out_size: 2
    num_layers: 1
    z_size: 64
    sigma: 1.3
    hidden_size: 64

    
    # obs_len: 8
    # pred_len: 12  # in timesteps
    

  # loss
  loss_function: 
    name: 'TrajCVAELoss'
    kwargs: {
      traj_weight: 1.0,
      kld_weight: 1
    }
      # loss_scale: 1000  # factor to scale the loss
#dataset

dataset:
  name: 'univ' # imageTraj or trajectory(not support)
  dataset_name: 'traj_dataset'
  num_goals: 1  # K_e
  num_traj: 20  # K_a
  train_data_path: '../dataset/univ/train'
  train_image_path: ''
  val_data_path: '../dataset/univ/test'
  val_image_path: ''
  test_data_path: '../dataset/univ/test'
  test_image_path: ''

  # data info
  # data_scale: 170
  resize: 1
  batch_size: 128
  obs_len: 8
  pred_len: 12
  num_workers: 4 
  prefetch_factor: 2
  # load_to_gpu: True
  # Ynet
  division_factor: 32 # use in Ynet the division factor must be 2^(len(encoder_channels))
  kernlen: 31  # (image) size of Gaussian kernel used for ground-truth Gaussian heatmap
  nsig: 4  # sigma of Gaussian kernel used for ground-truth Gaussian heatmap
  waypoints: ''
  # For semantic map
  segmentation_model_fp: ''
  semantic_classes: ''
  use_features_only: False  # If True the segmentation model only uses the

  #Sampler
  sampler: 
    name: 'custom' # custom or interval
    trainkwargs: {}
      # num_interval: 25 # for one epoch, the max num_interval for sampling
    valkwargs: {}
      # num_interval: 9999999 # for one epoch, the max num_interval for sampling
  collate_name: 'traj_collate' # scene_collate ,traj_collate,PECtraj_collate

optim:
  name: 'Adam'
  kwargs:
    lr: 0.00001
  # name: 'SGD_AGC'
  # kwargs:
  #     lr: 0.0001
  #     clipping: 0.16
    
  num_epochs: 100

# TEST

test:
  # TTST
  use_TTST: False
  rel_threshold: 0.01
  # CWS
  use_CWS: False
  CWS_params: None

  eval_step: 4
  temperature: 1.0
  round: 1

unfreeze: 150  # Unfreeze semantic segmentation model weights after this # of epochs
viz_epoch: 10
extra_info_name: 'datasetMeanStd' # constantFactor,inputTemplate,datasetMeanStd