experiment_name: 'RVNetTransformer_sdd_trajnet' 
device: 'cpu'

# MODEL
model:
  name: 'RVNetTransformer'
  pretrain: ''
  save_name: 'RVNetTransformer_sdd_traj'
  kwargs:
    num_samples: 64
    class_out: 16
    class_feat: [32]
    pred_len: 12
    pred_feat: [512,128]
    num_classes: 6
    num_heads: 8
    d_ff: 2048
    dropout: 0.1
    encoder_layer: 6
    use_transformer: True
    use_nonOrder: True
    
  # loss
  loss_function: 
    name: 'TrajMSELoss'
    kwargs: {}
      # loss_scale: 1000  # factor to scale the loss
#dataset

dataset:
  name: 'sdd'
  dataset_name: 'scene_dataset'
  num_goals: 1  # K_e
  num_traj: 20  # K_a
  train_data_path: '../dataset/SDD/train_trajnet.pkl'
  train_image_path: '../dataset/SDD/train'
  val_data_path: '../dataset/SDD/test_trajnet.pkl'
  val_image_path: '../dataset/SDD/test'
  test_data_path: '../dataset/SDD/test_trajnet.pkl'
  test_image_path: '../dataset/SDD/test'
  
  # data info
  resize: 0.5
  batch_size: 4
  obs_len: 8
  pred_len: 12
  num_workers: 4
  prefetch_factor: 1
  # load_to_gpu: True
  # Ynet
  division_factor: 32 # use in Ynet the division factor must be 2^(len(encoder_channels))
  kernlen: 31  # (image) size of Gaussian kernel used for ground-truth Gaussian heatmap
  nsig: 4  # sigma of Gaussian kernel used for ground-truth Gaussian heatmap
  waypoints: [11]
  # For semantic map
  segmentation_model_fp: segmentation_models/SDD_segmentation.pth
  initTrajectoryModelFilePath: init_models/PECNet_sdd0.5.pt
  num_points: 64
  semantic_classes: 6
  use_features_only: False  # If True the segmentation model only uses the

  #Sampler
  sampler: 
    name: 'interval' # custom or interval
    trainkwargs: {
      num_interval: 25 # for one epoch, the max num_interval for sampling
    }
    valkwargs:
      {
      num_interval: 9999999 # for one epoch, the max num_interval for sampling
    }
  collate_name: 'scene_collate'

optim:
  name: 'Adam'
  kwargs:
    lr: 0.00001
  # learning_rate: 0.0001
  num_epochs: 100

# TEST
test:
  # TTST
  use_TTST: False # the config is True
  rel_threshold: 0.01
  # CWS
  use_CWS: False
  CWS_params: None

  eval_step: 4
  temperature: 1.0
  round: 3

unfreeze: 150  # Unfreeze semantic segmentation model weights after this # of epochs
viz_epoch: 10
extra_info_name: 'inputTemplate'