resize: 0.25  # resize factor
batch_size: 4

viz_epoch: 10
learning_rate: 0.0001
num_epochs: 300

# list of selected goal and waypoints as timestep idx, e.g. 14 means the 14th future timestep is used as a waypoint,
# last element is goal timestep
waypoints:
  - 11

temperature: 1.0
segmentation_model_fp: segmentation_models/SDD_segmentation.pth
semantic_classes: 6

loss_scale: 1000  # factor to scale the loss

kernlen: 31  # (image) size of Gaussian kernel used for ground-truth Gaussian heatmap
nsig: 4  # sigma of Gaussian kernel used for ground-truth Gaussian heatmap

use_features_only: False  # If True the segmentation model only uses the
unfreeze: 150  # Unfreeze semantic segmentation model weights after this # of epochs

# TTST
use_TTST: True
rel_threshold: 0.01

# CWS
use_CWS: False
CWS_params: None

# DATASET
dataset_name: 'sdd'
train_data_path: '../dataset/SDD/train_trajnet.pkl'
train_image_path: '../dataset/SDD/train'
val_data_path: '../dataset/SDD/test_trajnet.pkl'
val_image_path: '../dataset/SDD/test'

num_goals: 20  # K_e
num_traj: 1  # K_a
experiment_name: 'sdd_trajnet' 

# MODEL
model:
  name: 'ynet'
  kwargs:
    obs_len: 8
    pred_len: 12  # in timesteps
    segmentation_model_fp: 'segmentation_models/inD_segmentation.pth'
    use_features_only: False # If True the segmentation model only uses the
    semantic_classes: 6
    encoder_channels: 
      - 32
      - 32
      - 64
      - 64
      - 64
    decoder_channels:
      - 64
      - 64
      - 64
      - 32
      - 32
# list of selected goal and waypoints as timestep idx, e.g. 14 means the 14th future timestep is used as a waypoint,
# last element is goal timestep
    waypoints:
      - 11


