experiment_name: 'sdd_trajnet' 
device: 'cuda:0'

# MODEL
model:
  name: 'ynet'
  pretrain: ''
  kwargs:
    obs_len: 8
    pred_len: 12  # in timesteps
    segmentation_model_fp: 'segmentation_models/inD_segmentation.pth'
    use_features_only: False # If True the segmentation model only uses the
    semantic_classes: 6
    encoder_channels: [32,32,64,64,64]
    decoder_channels: [64,64,64,32,32]
# list of selected goal and waypoints as timestep idx, e.g. 14 means the 14th future timestep is used as a waypoint,
# last element is goal timestep
    num_waypoints: 1
  temperature: 1.0
  # TTST
  use_TTST: True
  rel_threshold: 0.01

  # CWS
  use_CWS: False
  CWS_params: None
  # loss
  loss_function: 
    name: 'GoalTrajLoss'
    kwargs:
      loss_scale: 1000  # factor to scale the loss
#dataset

dataset:
  type: 'imageTraj' # imageTraj or trajectory(not support)
  dataset_name: 'sdd'
  num_goals: 20  # K_e
  num_traj: 1  # K_a
  train_data_path: '../dataset/SDD/train_trajnet.pkl'
  train_image_path: '../dataset/SDD/train'
  val_data_path: '../dataset/SDD/test_trajnet.pkl'
  val_image_path: '../dataset/SDD/test'
  test_data_path: '../dataset/SDD/test_trajnet.pkl'
  test_image_path: '../dataset/SDD/test'
  resize: 0.25
  batch_size: 4
  obs_len: 8
  pred_len: 12
  division_factor: 32 # use in Ynet the division factor must be 2^(len(encoder_channels))
  kernlen: 31  # (image) size of Gaussian kernel used for ground-truth Gaussian heatmap
  nsig: 4  # sigma of Gaussian kernel used for ground-truth Gaussian heatmap
  waypoints:
    - 11
  # For semantic map
  segmentation_model_fp: segmentation_models/SDD_segmentation.pth
  semantic_classes: 6
  use_features_only: False  # If True the segmentation model only uses the

  #Sampler
  sampler: 'interval' # custom or interval

optim:
  name: 'Adam'
  kwargs:
    lr: 0.0001
  # learning_rate: 0.0001
  num_epochs: 300
  
  unfreeze: 150  # Unfreeze semantic segmentation model weights after this # of epochs
  viz_epoch: 10


# list of selected goal and waypoints as timestep idx, e.g. 14 means the 14th future timestep is used as a waypoint,
# last element is goal timestep












