experiment_name: 'transformer_sdd_longterm' 
device: 'cuda:0'

# MODEL
model:
  name: 'transformer'
  pretrain: ''
  save_name: 'transformer_sdd_longterm'
  kwargs:
    enc_inp_size: 2
    dec_inp_size: 3
    dec_out_size: 3
    N: 6
    d_model: 512
    d_ff: 2048
    h: 8
    dropout: 0.1
    mean: [0,0]
    std: [0,0]
    # obs_len: 8
    # pred_len: 12  # in timesteps
    

  # loss
  loss_function: 
    name: 'pairwise_distance_loss'
    kwargs: {}
      # loss_scale: 1000  # factor to scale the loss
#dataset

dataset:
  name: 'sdd_longter' # imageTraj or trajectory(not support)
  dataset_name: 'traj_dataset'
  num_goals: 1  # K_e
  num_traj: 1  # K_a
  train_data_path: '../dataset/SDD/train_trajnet.pkl'
  train_image_path: ''
  val_data_path: '../dataset/SDD/test_trajnet.pkl'
  val_image_path: ''
  test_data_path: '../dataset/SDD/test_trajnet.pkl'
  test_image_path: ''

  # data info
  resize: 1.0
  batch_size: 100
  obs_len: 5
  pred_len: 30
  num_workers: 4 
  prefetch_factor: 2
  # load_to_gpu: True
  # Ynet
  division_factor: 32 # use in Ynet the division factor must be 2^(len(encoder_channels))
  kernlen: 31  # (image) size of Gaussian kernel used for ground-truth Gaussian heatmap
  nsig: 4  # sigma of Gaussian kernel used for ground-truth Gaussian heatmap
  waypoints: ''
  # For semantic map
  segmentation_model_fp: ''
  semantic_classes: ''
  use_features_only: False  # If True the segmentation model only uses the

  #Sampler
  sampler: 
    name: 'custom' # custom or interval
    trainkwargs: 
      factor: 0.2 # each epoch sampling 20% trajectoies from dataset
      # num_interval: 25 # for one epoch, the max num_interval for sampling
    valkwargs: {}
      # num_interval: 9999999 # for one epoch, the max num_interval for sampling
  collate_name: 'traj_collate'

optim:
  name: 'Noam'
  kwargs:
    emb_size: 512
    factor: 1.0
    warmup: 10
    lr: 0.0001
  # learning_rate: 0.0001
  num_epochs: 300

# TEST

test:
  # TTST
  use_TTST: False
  rel_threshold: 0.01
  # CWS
  use_CWS: False
  CWS_params: None

  eval_step: 10
  temperature: 1.0
  round: 1

unfreeze: 150  # Unfreeze semantic segmentation model weights after this # of epochs
viz_epoch: 10
extra_info_name: 'datasetMeanStd'